module.exports = {
			...require('project-rule-package/configs/commitlint/index.js'),
			...{
  ...require('project-rule-package/configs/commitlint/index.js'),
  ...{
    ...require('project-rule-package/configs/commitlint/index.js'),
    ...{
      ...require('project-rule-package/configs/commitlint/index.js'),
      ...{
        ...require('project-rule-package/configs/commitlint/index.js'),
        ...{
          ...require('project-rule-package/configs/commitlint/index.js'),
          ...{
            ...require('project-rule-package/configs/commitlint/index.js'),
            ...{
              ...require('project-rule-package/configs/commitlint/index.js'),
              ...{
                ...require('project-rule-package/configs/commitlint/index.js'),
                ...{
                  ...require('project-rule-package/configs/commitlint/index.js'),
                  ...{
                    ...require('project-rule-package/configs/commitlint/index.js'),
                    ...{
                      ...require('project-rule-package/configs/commitlint/index.js'),
                      ...{
                        ...require('project-rule-package/configs/commitlint/index.js'),
                        ...{
                          ...require('project-rule-package/configs/commitlint/index.js'),
                          ...{
                            ...require('project-rule-package/configs/commitlint/index.js'),
                            ...{
                              ...require('project-rule-package/configs/commitlint/index.js'),
                              ...{
                                ...require('project-rule-package/configs/commitlint/index.js'),
                                ...{
                                  ...require('project-rule-package/configs/commitlint/index.js'),
                                  ...{
                                    ...require('project-rule-package/configs/commitlint/index.js'),
                                    ...{
                                      ...require('project-rule-package/configs/commitlint/index.js'),
                                      ...{
                                        ...require('project-rule-package/configs/commitlint/index.js'),
                                        ...{
                                          ...require('project-rule-package/configs/commitlint/index.js'),
                                          ...{
                                            ...require('project-rule-package/configs/commitlint/index.js'),
                                            ...{
                                              ...require('project-rule-package/configs/commitlint/index.js'),
                                              ...{
                                                ...require('project-rule-package/configs/commitlint/index.js'),
                                                ...{
                                                  ...require('project-rule-package/configs/commitlint/index.js'),
                                                  ...{
                                                    ...require('project-rule-package/configs/commitlint/index.js'),
                                                    ...{
                                                      extends: ['@commitlint/config-conventional']
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
		};